/*
 * This file was automatically generated by EvoSuite
 * Sun Oct 13 17:58:58 GMT 2024
 */

package org.example.org.example;

import org.example.Conta;
import org.example.Conta_ESTest_scaffolding3;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Conta_ESTest33 extends Conta_ESTest_scaffolding3 {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Conta conta0 = new Conta((String) null, 0.0);
      try { 
        conta0.debitar(0.0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Conta", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Conta conta0 = new Conta("", (-2750.40393416152));
      double double0 = conta0.getSaldo();
      assertEquals((-2750.40393416152), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Conta conta0 = new Conta(":H>8)", 2719.1674);
      double double0 = conta0.debitar(1780.212);
      assertEquals(938.9553999999998, conta0.getSaldo(), 0.01);
      assertEquals(938.9553999999998, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Conta conta0 = new Conta("8eUH)I", (-1.0));
      double double0 = conta0.debitar(1485.3700678935556);
      assertEquals((-1486.3700678935556), conta0.getSaldo(), 0.01);
      assertEquals((-1486.3700678935556), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Conta conta0 = new Conta("8eUH)I", (-1.0));
      double double0 = conta0.creditar(1694.0);
      assertEquals(1693.0, conta0.getSaldo(), 0.01);
      assertEquals(1693.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Conta conta0 = new Conta("VkK%}ngZ", (-1407.5377341721));
      double double0 = conta0.creditar(760.13);
      assertEquals((-647.4077341721), conta0.getSaldo(), 0.01);
      assertEquals((-647.4077341721), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Conta conta0 = new Conta("", (-596.143177));
      try { 
        conta0.transferir(conta0, (-596.143177));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Conta", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Conta conta0 = new Conta("8eUH)I", (-1.0));
      double double0 = conta0.creditar(1.0);
      assertEquals(0.0, conta0.getSaldo(), 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Conta conta0 = new Conta(":H>8)", 2719.1674);
      conta0.debitar(2719.1674);
      double double0 = conta0.getSaldo();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Conta conta0 = new Conta(":H>8)", 2719.1674);
      try { 
        conta0.creditar(0.0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Conta", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Conta conta0 = new Conta("*1CXD.:n|Mn", (-15.221940413343326));
      try { 
        conta0.debitar((-1.0));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.example.Conta", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Conta conta0 = new Conta(":H>8)", 2719.1674);
      conta0.transferir(conta0, 2719.1674);
      assertEquals(2719.1674, conta0.getSaldo(), 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Conta conta0 = new Conta(":H>8)", 2719.1674);
      double double0 = conta0.getSaldo();
      assertEquals(2719.1674, double0, 0.01);
  }
}
